# Generated by Django 3.0.7 on 2021-04-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplyeeProfile',
            fields=[
                ('user_name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=250, null=True)),
                ('country', models.CharField(max_length=250, null=True)),
                ('contact_no', models.CharField(max_length=25, null=True)),
                ('passport_no', models.CharField(max_length=30, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=400, null=True)),
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayScale',
            fields=[
                ('designation', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('MA', models.BigIntegerField()),
                ('PF', models.BigIntegerField()),
                ('gross_pay', models.BigIntegerField()),
                ('net_pay', models.BigIntegerField()),
                ('basic_pay', models.BigIntegerField()),
                ('HRA', models.BigIntegerField()),
                ('TA', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfAddProfile',
            fields=[
                ('increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.EmplyeeProfile')),
            ],
        ),
        migrations.AddField(
            model_name='emplyeeprofile',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.PayScale'),
        ),
        migrations.AddField(
            model_name='emplyeeprofile',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile'),
        ),
    ]
