# Generated by Django 3.0.7 on 2021-04-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyeeprofile',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.PayScale'),
        ),
        migrations.AlterField(
            model_name='emplyeeprofile',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile'),
        ),
    ]
