# Generated by Django 3.0.7 on 2021-04-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountDetails',
            fields=[
                ('discount_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('month_valid', models.CharField(max_length=4)),
                ('min_stay', models.CharField(max_length=30)),
                ('offer_percent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HotelProfile',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('contact_no', models.CharField(max_length=250)),
                ('owner_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_status', models.CharField(choices=[('A', 'Available'), ('B', 'Booked'), ('C1', 'Cancelled by user'), ('C2', 'Cancelled by hotel')], max_length=2)),
                ('check_in_date', models.CharField(max_length=15)),
                ('check_out_date', models.CharField(max_length=15)),
                ('check_in_time', models.CharField(max_length=15)),
                ('check_out_time', models.CharField(max_length=15)),
                ('total_guests', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('reservation_date', models.CharField(max_length=15)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.DiscountDetails')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.GuestDetails')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=250)),
                ('price_per_day', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('room_key', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.PositiveIntegerField(null=True)),
                ('layout', models.CharField(max_length=40)),
                ('floor_no', models.PositiveIntegerField(default=0)),
                ('room_status', models.CharField(max_length=1)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.GuestDetails')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.ReservationDetails')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.RoomPrice')),
            ],
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.RoomPrice'),
        ),
        migrations.CreateModel(
            name='DiscountDistribution',
            fields=[
                ('distribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.DiscountDetails')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.GuestDetails')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile')),
            ],
        ),
        migrations.AddField(
            model_name='discountdetails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile'),
        ),
        migrations.AddField(
            model_name='discountdetails',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.RoomPrice'),
        ),
    ]
