# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_status', models.CharField(choices=[('A', 'Availed'), ('B', 'Booked'), ('C1', 'Cancelled by user'), ('C2', 'Cancelled by hotel')], max_length=2)),
                ('check_in_date', models.CharField(max_length=15)),
                ('check_out_date', models.CharField(max_length=15)),
                ('check_in_time', models.CharField(max_length=15)),
                ('check_out_time', models.CharField(max_length=15)),
                ('total_guests', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('reservation_date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountAvailed',
            fields=[
                ('availed_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountDetails',
            fields=[
                ('discount_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('month_valid', models.CharField(max_length=4)),
                ('length_of_stay', models.CharField(max_length=30)),
                ('offer_percent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HotelProfile',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('reg_no', models.CharField(max_length=250)),
                ('contact_no', models.CharField(max_length=250)),
                ('owner_name', models.CharField(max_length=250)),
                ('owner_email', models.CharField(max_length=250)),
                ('owner_contact_no', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('room_key', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.PositiveIntegerField(null=True)),
                ('layout', models.CharField(max_length=40)),
                ('floor_no', models.PositiveIntegerField(default=0)),
                ('nru', models.CharField(max_length=250)),
                ('room_status', models.CharField(max_length=1)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.ReservationDetails')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.GuestDetails')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPriceDetails',
            fields=[
                ('room_type', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('price_per_day', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile')),
            ],
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.RoomPriceDetails'),
        ),
        migrations.AddField(
            model_name='discountdetails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile'),
        ),
        migrations.AddField(
            model_name='discountdetails',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.RoomPriceDetails'),
        ),
        migrations.AddField(
            model_name='discountavailed',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.DiscountDetails'),
        ),
        migrations.AddField(
            model_name='discountavailed',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.GuestDetails'),
        ),
        migrations.AddField(
            model_name='discountavailed',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile'),
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.DiscountDetails'),
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.GuestDetails'),
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.HotelProfile'),
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.RoomPriceDetails'),
        ),
    ]
