# Generated by Django 3.0.7 on 2021-04-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdetails',
            name='reservation_status',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Booked'), ('C1', 'Cancelled by user'), ('C2', 'Cancelled by hotel')], max_length=2),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.GuestDetails'),
        ),
    ]
