# Generated by Django 3.0.7 on 2021-04-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdetails',
            old_name='room',
            new_name='room_price',
        ),
        migrations.RemoveField(
            model_name='roomdetails',
            name='hotel',
        ),
    ]
