# Generated by Django 3.0.7 on 2021-04-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('reservations', '0002_auto_20210404_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.GuestDetails'),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.ReservationDetails'),
        ),
    ]
