# Generated by Django 3.0.7 on 2021-04-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210409_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountdetails',
            old_name='room',
            new_name='room_class',
        ),
        migrations.RenameField(
            model_name='reservationdetails',
            old_name='room_price',
            new_name='room_class',
        ),
        migrations.RenameField(
            model_name='roomdetails',
            old_name='room',
            new_name='room_class',
        ),
    ]
