# Generated by Django 3.0.7 on 2021-04-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20210409_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomprice',
            old_name='price_id',
            new_name='class_id',
        ),
    ]
