# Generated by Django 3.0.7 on 2021-04-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20210404_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdetails',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.DiscountDetails'),
        ),
    ]
