# Generated by Django 3.0.7 on 2021-04-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210409_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomPrice',
            new_name='RoomClass',
        ),
    ]
