# Generated by Django 3.0.7 on 2021-04-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20210409_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountdetails',
            name='hotel',
        ),
    ]
