# Generated by Django 3.0.7 on 2021-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_discountdetails_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountdetails',
            name='min_stay',
        ),
        migrations.AddField(
            model_name='discountdetails',
            name='min_nights',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
