# Generated by Django 3.0.7 on 2021-04-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20210409_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdetails',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationdetails',
            name='check_out_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationdetails',
            name='reservation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservationdetails',
            name='reservation_status',
            field=models.CharField(choices=[('B', 'Booked'), ('C1', 'Cancelled by user'), ('C2', 'Cancelled by hotel')], max_length=2),
        ),
    ]
