# Generated by Django 3.0.7 on 2021-04-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20210420_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetails',
            name='room_status',
        ),
    ]
