# Generated by Django 3.0.7 on 2021-04-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_roomdetails_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetails',
            name='guest',
        ),
    ]
