# Generated by Django 3.0.7 on 2021-04-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_remove_roomdetails_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationdetails',
            name='room_class',
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.ReservationDetails')),
                ('room_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.RoomDetails')),
            ],
        ),
    ]
