# Generated by Django 3.0.7 on 2021-04-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_auto_20210423_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetails',
            name='reservation',
        ),
    ]
